name: Deploy docs

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        working-directory: ./docs
        run: pnpm install
      - name: Build
        working-directory: ./docs
        run: pnpm docs:build
      - name: deploy
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SERVER }}
          port: 22
          user: ${{ secrets.SERVER_LOGIN }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          localDir: './docs/.vitepress/dist'
          remoteDir: ${{ secrets.TARGET_DIR }}
          reverse: true
